[package]
name = "rsa"
version = "0.1.0"
authors = ["redshiftzero <jen@freedom.press>"]
edition = "2018"

[dependencies]
num = "0.3.1"
num-bigint = {version = "0.3.1", features = ["rand"] }
primes = { path = "../primes" }
lazy_static = "1.4.0"
hex = "0.4.2"
