[workspace]

members = [
    "block_ciphers",
    "classic_ciphers",
    "primes",
    "diffie_hellman",
    "rsa",
    "mac",
    "hashes",
    "hmac",
    "hmac_server",
    "secure_remote_password",
    "utils",
]
